// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9HTrtq3-WGUQHQeglisGUDdhOmZoJud8',
    appId: '1:311112158751:web:409876758072c6fe714f2a',
    messagingSenderId: '311112158751',
    projectId: 'tendencias-595fc',
    authDomain: 'tendencias-595fc.firebaseapp.com',
    storageBucket: 'tendencias-595fc.appspot.com',
    measurementId: 'G-YS67YF53LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQepdZfr-exeK9hX4x715WT_vhaY5XlO0',
    appId: '1:311112158751:android:0d64d19640b3a3cd714f2a',
    messagingSenderId: '311112158751',
    projectId: 'tendencias-595fc',
    storageBucket: 'tendencias-595fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK9E8S0QZcS413no8ALXYFI-kXCokPOEY',
    appId: '1:311112158751:ios:e6c43a4926ac7f0d714f2a',
    messagingSenderId: '311112158751',
    projectId: 'tendencias-595fc',
    storageBucket: 'tendencias-595fc.appspot.com',
    iosClientId: '311112158751-oa4rt58dgssq9f6ba6k81b7acimmamuq.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.flutterTendencias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK9E8S0QZcS413no8ALXYFI-kXCokPOEY',
    appId: '1:311112158751:ios:5d730ad590d81b2e714f2a',
    messagingSenderId: '311112158751',
    projectId: 'tendencias-595fc',
    storageBucket: 'tendencias-595fc.appspot.com',
    iosClientId: '311112158751-j74vemsif3and469sufhpsgkov2rjt2t.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.flutterTendencias.RunnerTests',
  );
}
